### ISSUE TITLE
Let the user choose what format to save the song as

### ISSUE THREAD

**Issue by redcathode** [rickyrorton/spotify-downloader#1]
In its current state, this downloader only allows the user to transcode lossy YouTube AAC/OPUS audio to a lossy mp3. Would it be possible to also allow downloading an m4a directly from YouTube without transcoding the audio? This would lead to higher quality downloads with a lower filesize.

**Comment by rickyrorton** [comment]
sure will try to add that too in a drop down menu

**Comment by rickyrorton** [comment]
this has now been added please check the new updates
