### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by Combine900** [rickyrorton/spotify-downloader#10]
Hey, could you may put a paypal donation link or something else where we can support your work?

**Comment by rickyrorton** [comment]
Hey thank you for the kind gesture but I currently do not own a paypal account ,once I do open one in the near future I will put a donation link in the readme/docs

**Comment by rickyrorton** [comment]
I have finally opened a paypal account feel free to donate any amount you like:https://paypal.me/rickyrorton ill put it in the docs too
