### ISSUE TITLE
Unable to find song on yt, fails to download

### ISSUE THREAD

**Issue by jzuniga3** [rickyrorton/spotify-downloader#11]
Hello! On some songs they do not download since they are not found on youtube. It says to alert devs so unsure what to do. Thank you!
Here are some songs it happened on: 

https://open.spotify.com/track/6SFlPCWD6TCDlQ26GOQhUc?si=a5083ca1127847ee
https://open.spotify.com/track/24wV4nvuXpAoflBSsq3FAP?si=1db76855aec6466e
![Capture](https://user-images.githubusercontent.com/78007973/176172960-779c5a5e-54cb-41f1-91dc-de5f86743f43.PNG)

**Comment by rickyrorton** [comment]
If you can find the youtube links for songs you can join the discord and add them through the bot to the database so it gets downloaded next time

**Comment by jzuniga3** [comment]
Thank you so much!
