### ISSUE TITLE
WINERROR 2

### ISSUE THREAD

**Issue by BHN12345** [rickyrorton/spotify-downloader#14]
Hello, When i choose the mp3 format. It's always says WINERROR 2. What can i do?

**Comment by rickyrorton** [comment]
Kindly install the ffmpeg executables properly (the 3 ffmpeg exes from the bin folder in the ffmpeg.7z archive)(Place the 3 exes in the same directory as the program)

**Comment by rickyrorton** [comment]
@BHN12345  you no longer have to install the exes yourself kindly download the latest release the program now automatically installs it for you
