### ISSUE TITLE
latest release asks for an update

### ISSUE THREAD

**Issue by Skywalker25** [rickyrorton/spotify-downloader#15]
the latest release file v1.70 when run asks to update exe to the latest v1.70. it seems the version number was bumped in github but not in the file it self. it still thinks it's v1.68.

**Comment by lanadelplaya** [comment]
I can confirm this above statement, even after downloading and adding to path, it still asks the user to redownload, also, the gui portion will crash upon ANY and ALL changes made via the gui as well! Previous version worked F L A W L E S S L Y.

**Comment by lanadelplaya** [comment]
Thank you @dev by the way, for this project. It is great to utilize!

**Comment by lanadelplaya** [comment]
also figured out what to do with this scenario to stop crashing/asking for the latest repo, open "downloader.py" in any text editor, remove all this sectioning:

**Comment by lanadelplaya** [comment]
def checkversion():
    response = (
        get(
            "https://api.github.com/repos/rickyrorton/spotify-downloader/releases/latest"
        )
    ).json()
    data = response["tag_name"]
    if data.lower() != __version__.lower():
        ch = messagebox.askokcancel(
            "UPDATE APP",
            f"Press OK to update your app to the latest version {data} from the github repository",
        )
        if ch:
            from webbrowser import open_new_tab

            open_new_tab("https://github.com/rickyrorton/spotify-downloader/releases")
        elif __name__ != "__main__":
            exit()


t = Thread(target=checkversion())
t.start()
t.join()

**Comment by lanadelplaya** [comment]
save the copy of the "downloader.py" back in the file, and open your cmd.exe/terminal.app and cd the spotify-downloader folder you saved it to.

also for the latest version, you can also just "git clone "download repo link insertion here" after deleting the previous spotify-downloader file from git

**Comment by rickyrorton** [comment]
> the latest release file v1.70 when run asks to update exe to the latest v1.70. it seems the version number was bumped in github but not in the file it self. it still thinks it's v1.68.

@Skywalker25 yes i had forgot to update the version variable to v1.7 so the program thinks it was 1.68 even tho it was v1.7 I have fixed this issue now and modified the v1.7 release you can redownload the exe and it should be fixed, I apologize for the inconvenience caused.

**Comment by rickyrorton** [comment]
> can confirm this above statement, even after downloading and adding to path, it still asks the user to redownload, also, the gui

gui.py was fine as is.The downloader.py file required a minor change.The change is:
``` __version__ = "v1.7"``` from ```__version__ = "v1.68"``` on line 28

**Comment by rickyrorton** [comment]
> def checkversion(): response = ( get( "https://api.github.com/repos/rickyrorton/spotify-downloader/releases/latest" ) ).json() data = response["tag_name"] if data.lower() != **version**.lower(): ch = messagebox.askokcancel( "UPDATE APP", f"Press OK to update your app to the latest version {data} from the github repository", ) if ch: from webbrowser import open_new_tab
> 
> ```
>         open_new_tab("https://github.com/rickyrorton/spotify-downloader/releases")
>     elif __name__ != "__main__":
>         exit()
> ```
> 
> t = Thread(target=checkversion()) t.start() t.join()

kindly do not modify version checker code
