### ISSUE TITLE
Program fails to convert songs with symbols in the name

### ISSUE THREAD

**Issue by marcopg99** [rickyrorton/spotify-downloader#2]
When the song has "/" in the name (AC/DC for example):
- Couldnt convert song [Errno 2] No such file or directory : file path.mp3

When the song has "?" in the name:
- Couldnt convert song [Errno 22] Invalid argument: file path.mp3

**Comment by marcopg99** [comment]
When it has ":" in the name, a file without extension is left in the download directory. No error message shown

**Comment by Vildis** [comment]
Windows doesn't allow the following characters in filenames:  
`/ \ ? % * : | < and >`  [Wikipedia](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words) 

Easiest fix is just to remove them in the code.

**Comment by Vildis** [comment]
Removing the characters might not work in all cases if the song name is only symbols.
No clue what to do then, song name would still show in file metadata.

**Comment by rickyrorton** [comment]
i did encounter the same problem and fixed it only for one character, ill do for the others too
