### ISSUE TITLE
Convetred files are m4a instead of mp3

### ISSUE THREAD

**Issue by jlnhlfan** [rickyrorton/spotify-downloader#5]
In the past, converted files were of the .mp3 format, which works well with EA's NHL video games, which had a custom soundtrack feature on the PS3. However, the most recent update now has converted files be of the .m4a format, which is not supported by these games (teh fact that unconverted files are of the .mp4 format doesn't help). Is there anything that could be done about this?

**Comment by rickyrorton** [comment]
I have updated the code to include conversion to mp3 kindly download the latest version and enjoy!
Note:
For mp3 ffmpeg needs to be installed and added to path
