### ISSUE TITLE
Virus 3/69 detected malware is it something to worry about

### ISSUE THREAD

**Issue by kekkodance** [rickyrorton/spotify-downloader#8]
the exe file provided in the repo should:
not be included in the repo itself, but as a release
not weigh 20MB, the author's excuse being "additional libraries"
not show up on virustotal, as shown [here](https://www.virustotal.com/gui/file/cc203db0cb38b3467f3970562f67328b615f768a1351c2f3776823ccb11a5226/detection)
not have a TCP call to a VPS owned by akamai on launch

it seems pretty suspicious, i would honestly use other downloaders on GitHub.

**Comment by kekkodance** [comment]
another thing is that both of the creators insist to friend request me on discord to talk and disprove their point, instead of coming on GitHub.
![image](https://user-images.githubusercontent.com/53054786/161430088-a3e995c2-8ccf-4a5f-b318-9d122d0ce1f2.png)

**Comment by lodu** [comment]
Virus total flagging 3/69 can be a false positive tho. Happens with plenty of programs.

**Comment by kekkodance** [comment]
> Virus total flagging 3/69 can be a false positive tho. Happens with plenty of programs.

still doesn't make sense, why would they upload the exe to the repo like that? why would they be this scummy and not try to defend themselves on here?
why would the exe dump this stuff in the temp folder?
![image](https://user-images.githubusercontent.com/53054786/161432073-4aa7b544-d777-4be7-8e92-2d5dcad6b035.png)

**Comment by rickyrorton** [comment]
The ip address that belongs to Akamai is used by spotify and my program uses the spotify api 
![image](https://user-images.githubusercontent.com/74890659/161436477-5bd3645d-cb31-44ef-be49-3749d1af48bf.png)
also its being flagged unsafe only by 3 antiviruses these are probably false positives

**Comment by rickyrorton** [comment]
The files written you are seeing are time zone data which is utilised by the time module in the program

**Comment by the-batfish** [comment]
you are very naive if you think 3/69 on virustotal immediately proves that its a virus.

**Comment by the-batfish** [comment]
> you are very naive if you think 3/69 on virustotal immediately proves that its a virus.

not to mention the three antiviruses that flagged it are completely unheard of. [This](https://www.virustotal.com/gui/file/8e5127c45a8a3d062fca49eaff782fa91b32f83a82cc050087fb26d16b9b6d60?nocache=1) is what a real virus looks like on virust total.

Also the reason we added the .exe was for the sake of ease of use.

**Comment by the-batfish** [comment]
>why would the exe dump this stuff in the temp folder?
like the author said, that is time zone data. Its not us. we believe its being done by the time module we have in the python script.

**Comment by adikpb** [comment]
> the author's excuse being "additional libraries"

These are the modules/libraries used in the script

**downloader.py**

```from os import path as ospath
from os import remove,rename
from unicodedata import name
from urllib import request
from mutagen.mp4 import MP4,MP4Cover
from mutagen.id3 import ID3,TIT2,APIC,TALB,TPE1,TPE2,TYER,TRCK
from pytube import YouTube
from spotipy import Spotify
from spotipy.oauth2 import SpotifyClientCredentials
from youtube_search import YoutubeSearch
from threading import Thread
from datetime import datetime
from pydub import AudioSegment
from tkinter import messagebox
from mysql.connector import connect
```

**gui.py**

```from tkinter import Entry, StringVar, Tk,Button,Label,scrolledtext,LabelFrame,CENTER,OptionMenu,Scale, HORIZONTAL,LEFT#tkinter for the user interface
from PIL import Image,ImageTk #Python(PIL) image library for inserting images into the user interface
from tkinter.filedialog import askdirectory
from tkinter.ttk import Progressbar
import sys
from os import path as ospath
import downloader
from webbrowser import 
```

**Comment by adikpb** [comment]
> > the author's excuse being "additional libraries"
> 
> These are the modules/libraries used in the script
> 
> **downloader.py**
> 
> ```
> from os import remove,rename
> from unicodedata import name
> from urllib import request
> from mutagen.mp4 import MP4,MP4Cover
> from mutagen.id3 import ID3,TIT2,APIC,TALB,TPE1,TPE2,TYER,TRCK
> from pytube import YouTube
> from spotipy import Spotify
> from spotipy.oauth2 import SpotifyClientCredentials
> from youtube_search import YoutubeSearch
> from threading import Thread
> from datetime import datetime
> from pydub import AudioSegment
> from tkinter import messagebox
> from mysql.connector import connect
> ```
> 
> **gui.py**
> 
> ```
> from PIL import Image,ImageTk #Python(PIL) image library for inserting images into the user interface
> from tkinter.filedialog import askdirectory
> from tkinter.ttk import Progressbar
> import sys
> from os import path as ospath
> import downloader
> from webbrowser import 
> ```

All these together make the exe come upto around 20 MB or so. BTW the exe is compilled using pyinstaller. Let us personally know if you would like to try to compile it.

**Comment by rickyrorton** [comment]
> another thing is that both of the creators insist to friend request me on discord to talk and disprove their point, instead of coming on GitHub. ![image](https://user-images.githubusercontent.com/53054786/161430088-a3e995c2-8ccf-4a5f-b318-9d122d0ce1f2.png)

So firstly I do not get in app notification for issues I only get mail notifications for issues  and i rarely see my mail which should explain why i did not talk on github and tried to dm you but instead you werent willing to listen and thats why i told my friend to dm you and try to make you understand that our program isnt malware

**Comment by itslychee** [comment]
> > Virus total flagging 3/69 can be a false positive tho. Happens with plenty of programs.
> 
> still doesn't make sense, why would they upload the exe to the repo like that? why would they be this scummy and not try to defend themselves on here? why would the exe dump this stuff in the temp folder? ![image](https://user-images.githubusercontent.com/53054786/161432073-4aa7b544-d777-4be7-8e92-2d5dcad6b035.png)

just because they upload a binary to the git tree does not mean it is scummy, by that logic every file uploaded to a git remote should be considered just as scummy.

You should also realize that antivirus programs are not perfect, and occasionally when i write Go applications on Windows it wrongly flags it as a trojan virus, which it is not.
